### ISSUE TITLE
Nacho López - ejercicios/00_hola_mundo.py - Error en la función print

### ISSUE THREAD

**Issue by milq** [milq/si#1]
¡Ayuda! ¡No me funciona la función _print_!

`pint('hola mundo')`

**Comment by Fernan2David** [comment]
Le falta la r a print.
un saludo amigo

**Comment by Coski69** [comment]
debes escribir print

**Comment by Beiroa013** [comment]
No tiene la "r" final

**Comment by biosrota** [comment]
se escribe print
P.D gracias por el wifi

**Comment by riskrompar** [comment]
La orden es "print" no pint

**Comment by thewalkerofdreams** [comment]
+rt Fernan2David

**Comment by Pirosmano** [comment]
eso va a ser que tienes que resetear la bios

**Comment by Ramtor** [comment]
Es print, no pint

**Comment by roto2** [comment]
Es print, no pint

**Comment by macnolillo** [comment]
Mi compañero de la izquierda empuja el culo pa dentro

**Comment by Pirosmano** [comment]
tienes que resetar la bios!

**Comment by biosrota** [comment]
taringa 2.0

**Comment by Moicasas** [comment]
Nuubs¡

**Comment by Beiroa013** [comment]
Hola soy el hombre mierda

**Comment by Pirosmano** [comment]
reprot afk feeder

**Comment by Ramtor** [comment]
MANCO!

**Comment by LAZA-05** [comment]
:O

**Comment by macnolillo** [comment]
Vendo opelcorsa plata 1.6  gasolina, buen estado, 120000km precio a convenir

**Comment by LAZA-05** [comment]
@Coski69

**Comment by riskrompar** [comment]
Yeray esta interesado en opel corsa

**Comment by Ramtor** [comment]
rt, like y fav

**Comment by Ramtor** [comment]
Yery estás más fuerte que el limón HOSTIA!

**Comment by Pirosmano** [comment]
yery te han actualizado el README

**Comment by Moicasas** [comment]
Subo cuenta de lol a caambio de skin¡

**Comment by LAZA-05** [comment]
open

**Comment by Ramtor** [comment]
Migue menos overwatch y más wow carajo

**Comment by thewalkerofdreams** [comment]
migue ;)

**Comment by Pirosmano** [comment]
ESTO VA A SER COSA DE LA BIOS

**Comment by riskrompar** [comment]
close, deja la ventana encaja

**Comment by Moicasas** [comment]
Subo cuenta de lol a cambio de skin¡

**Comment by Coski69** [comment]
que pite ya por diosssssssss

**Comment by macnolillo** [comment]
Yeray tiene un fallo en el crecimiento, que no le afecta al pene, escribe amen y dale a like para que se cure

**Comment by biosrota** [comment]
https://www.youtube.com/watch?v=2pq_rjxJIRk

**Comment by Beiroa013** [comment]
amen

**Comment by riskrompar** [comment]
amen

**Comment by LAZA-05** [comment]
toma ti like    8=====D

**Comment by Pirosmano** [comment]
AMEN

**Comment by Beiroa013** [comment]
mis dieses

**Comment by Fernan2David** [comment]
amen,

**Comment by Ramtor** [comment]
no puedo decir amen, soy ateo, pero tienes mi like ;)

**Comment by Pirosmano** [comment]
<img src="https://frieze.com/sites/default/files/editorial/tumblr_n2mzdeqyqp1rzfa3ao1_500.gif" alt="kakapo"/>
